### ISSUE TITLE
Async architecture

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchy#10]
We lock ST3 a lot right now.  This is mostly because SK sometimes takes more time to get back to us.

What we need to do is make more async requests.  
- There's a method to do this inside SK, but I haven't investigated it in depth
- The anaconda plugin is somehow able to get back to ST3 asynchronously, I suppose we should look into how they achieve it

**Comment by dunkelstern** [comment]
Just spawning a thread does not work? I never used that c library interface, it could be that it blocks all threads, but i suppose not.

**Comment by drewcrawford** [comment]
My understanding is that blocking one Python thread blocks them all due to GIL.  Do you know something I don't?

**Comment by dunkelstern** [comment]
From python docs:

>  Note that potentially blocking or long-running operations, such as I/O, image processing, and NumPy number crunching, happen outside the GIL. Therefore it is only in multithreaded programs that spend a lot of time inside the GIL, interpreting CPython bytecode, that the GIL becomes a bottleneck.

So if the lockup is because we're waiting for SK the GIL should not be triggered.
