### ISSUE TITLE
Build from ST

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchy#13]
AFAIK you are/were working on this.  I tried to use it today (not sure of current state) without success.

Here were my attempts, what am I doing wrong:
1.  Cmd-B (invokes random buildsystem)
2.  Tools->Build system->Look for something Swift or AT-related 
   
   <img width="222" alt="screen shot 2016-04-01 at 11 13 39 pm" src="https://cloud.githubusercontent.com/assets/183400/14224379/65788ae4-f85f-11e5-95f7-bcb4938bb27b.png">
3.  "Use the source, luke", discover `atpkg.sublime-commands` which seems related
4.  Okay, maybe we build with the command palette?
5.  Cmd-Shift-P, search for "Anarchy"
   
   <img width="565" alt="screen shot 2016-04-01 at 11 14 29 pm" src="https://cloud.githubusercontent.com/assets/183400/14224384/8e8b7306-f85f-11e5-8ca0-5b61aebedfc5.png">
6.  Give up, file issue

**Comment by dunkelstern** [comment]
Are you working with a project file or "just opened the directory in sublime"?

Currently the commands only show up if you have loaded a project file as i am not sure how to find the correct project root without that and how to manage what happens if you have multiple instances of a file in different windows.

**Comment by dunkelstern** [comment]
Build systems in sublime are not really good enough™ to allow for our need to display targets, etc. We could offer a build system that just builds `default` but then the colored output of the build command and all of the error markers won't work. You probably could hack something but i think it won't work in all cases.

**Comment by drewcrawford** [comment]
> just opened the directory in sublime

That's it, thanks.  Let's put this in the readme?

FYI, this is pretty amazing.  A few notes:
1.  We should set `atbuild_path` to `/usr/local/bin/atbuild` which is a better default.  Obviously, we need some way to override if we don't have it already.
2.  We should create a keyboard binding for "build the last thing again"?
3.  Right now the little "error dot" follows me around from file to file, often at a silly location, e.g.
   
   <img width="609" alt="screen shot 2016-04-02 at 3 26 28 pm"   src="https://cloud.githubusercontent.com/assets/183400/14228837/512c6532-f8e7-11e5-8ab4-d519ebfd6b46.png">
   
   <img width="364" alt="screen shot 2016-04-02 at 3 26 38 pm" src="https://cloud.githubusercontent.com/assets/183400/14228839/59810fda-f8e7-11e5-848e-ae646f3b2b79.png">
4.  IMO the "inline errors" feature (perhaps _in addition_ to being powered from a build) should also be powered via SK.  The difference is, Xcode can find errors as you type, without having to build explicitly.  IMO that is a good behavior.

**Comment by dunkelstern** [comment]
You can override the atbuild path, let me add some menu entries to make it more visible. The default "Default Config" -> "User Config" of sublime should work just fine.

I'll look why the error dot follows you, that's strange indeed.

SK support for inline errors would be very cool. I would let the build process override the "as you type" error badges, perhaps only hilight the line with an error if SK thinks it's an error and keep the badges without hilight for the compiler?

**Comment by dunkelstern** [comment]
Documentation is in Readme about where to find the build command, error marker is fixed, execute last build is in. Closing
