### ISSUE TITLE
Protocols break syntax highlighting

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchy#14]
<img width="488" alt="screen shot 2016-04-02 at 5 44 15 pm" src="https://cloud.githubusercontent.com/assets/183400/14229482/92b2a882-f8fa-11e5-8594-edb526a4b3d5.png">

@dunkelstern

**Comment by dunkelstern** [comment]
Ok found it, was not the protocol that trashed the hilighter but the function prototype (has no { as end marker)

I probably broke multi-line function definitions now, at least in some cases, if someone finds such a case submit a new bug.
