### ISSUE TITLE
Syntax highlight bug: nested comments

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchy#15]
Another fun highlighting bug.

<img width="1056" alt="screen shot 2016-04-07 at 1 00 24 am" src="https://cloud.githubusercontent.com/assets/183400/14342020/31b93fa4-fc5c-11e5-8dd6-e87bd6f6548a.png">
1.  Swift allows nested comments
2.  We have a comment referencing the string `src/**.swift`
3.  Swift detects this as a comment open
4.  To satisfy swift, we include a random comment close
5.  SublimeAnarchy highlighter thinks we are exiting the outer comment, not the nested one.

@dunkelstern

**Comment by dunkelstern** [comment]
Very strange behaviour... has this a SR?

**Comment by drewcrawford** [comment]
I believe the swift behavior is expected–Swift supports nested comments.

The issue seems to be that we do not.
