### ISSUE TITLE
Syntax highlighting: assorted atpkg

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchy#17]
@dunkelstern 

<img width="868" alt="screen shot 2016-04-07 at 5 10 06 am" src="https://cloud.githubusercontent.com/assets/183400/14347956/3ac11464-fc7f-11e5-8ae8-8ae716464368.png">

Note that, I am in the process of writing new atpkg tools, so some errors are expected, but these two are not.

**Comment by dunkelstern** [comment]
the two tasks `check` and `default` have a special class to stand out, link options was just left out i guess, i'll fix that
