### ISSUE TITLE
dotted keys

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchy#18]
In a future release of atbuild, we will be introducing some well-known dotted keys.

<img width="431" alt="screen shot 2016-04-12 at 12 22 23 am" src="https://cloud.githubusercontent.com/assets/183400/14450537/d2dd6d10-0044-11e6-843f-1b9d703388bf.png">

Currently it seems that syntax highlighting assumes a `.` terminates a key (even if not well-known).

@dunkelstern

**Comment by dunkelstern** [comment]
ok i'll fix it so unknown keys allow dots, we should probably promote them to known keys later on or define a rule that a dot extension is possible for known keys.
