### ISSUE TITLE
Multi-file projects

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchy#6]
I assume we parse the atpkg to figure this out, but the question is, which task do we look at?

**Comment by dunkelstern** [comment]
Suggestion: We need a task selector for building either way, so we could use the last built task or default if nothing has been built yet

**Comment by drewcrawford** [comment]
`taskForSourceFile` is able to guess the task based on the (open) sourcefile, but if there are more than one task involving that sourcefile the result is ambiguous.
